// <auto-generated />
namespace Final_Project_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editedalbummodelclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedalbummodelclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201611212342165_edited album model class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
